name: cyberbully_text_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - scikit-learn
  - tqdm
  - pip
  - pip:
    - transformers
    - demoji
